### PR TITLE
Add marketing dialog

### PR DESCRIPTION
**Pull request by lorgan3**
### Description

We're moving the implementation of the Marketing Dialog to the ui library so we can have a consistent and documented dialog for this everywhere.

#### Screenshot before this PR

/

#### Screenshot after this PR

image

### Breaking changes

/

### CODE REVIEW

**Review by jelledc — APPROVED** [review]

**Review by farazatarodi — DISMISSED** [review]

**Comment by jelledc** [comment]
Manually tested. Works well!

Q: Is it intentional that these buttons aren't the same width? It only becomes clear when hovering over the bottom one.

image

**Review by eniskraasniqi1 — DISMISSED** [review]

**Comment by lorgan3** [comment]
@jelledc I'll double check that with design!

**Review by lowiebenoot — APPROVED** [review]

**Review by JorenSaeyTL — APPROVED** [review]

**Comment by lorgan3** [comment]
@jelledc Should indeed be full width, quickly updating it now!

**Review by KristofColpaert — APPROVED** [review]

**Review by JorenSaeyTL — APPROVED** [review]

**Review by eniskraasniqi1 — APPROVED** [review]

**Comment by eniskraasniqi1** [comment]
Checking... ⌛

**Comment by eniskraasniqi1** [comment]
Checked ✅

**Pull request merged**
