### PR TITLE
Checkbox: apply 'position: absolute;' to the input element

### PR DESCRIPTION
**Pull request by driesd**
### Description

This PR fixes a margin issue with our `Checkbox` component in `Firefox on Linux`.

### Breaking changes

None.

### CODE REVIEW

**Comment by jnstr** [comment]
What's the easiest way to manually test this?

**Comment by driesd** [comment]
> What's the easiest way to manually test this?

Checkout this PR and in your console type `npm start`. Then navigate to the [checkbox component in your local Storybook](http://localhost:3000/?path=/story/form-elements-checkbox--default). Make sure you're on Firefox on your Linux machine ;)

**Comment by jnstr** [comment]
Manually checked :heavy_check_mark: 

@Kemosabert `visibility: hidden` didn't work since the main problem was that the width of the default browser checkbox was still reserved and setting the visibility on hidden still reserves the width of the element.

**Comment by Kemosabert** [comment]
@jnstr thanks for clarifying! :)

**Pull request merged**
