### PR TITLE
Fix: disabled and read-only on ie11

### PR DESCRIPTION
**Pull request by TaraldRotsaert**
### Description

- Separated the grouped css for the disabled and read-only props of input elements, otherwise, this code doesn't get executed on IE11.

#### Screenshot before this PR

Schermafdruk 2019-03-22 09 45 27

#### Screenshot after this PR

Schermafdruk 2019-03-22 09 45 42

### Breaking changes

None

### CODE REVIEW

**Comment by mikeverf** [comment]
Q: Do the `readOnly` and `disabled` attributes actually *disable* the inputs too on IE? It should, but you never know with IE :)

**Comment by driesd** [comment]
> Q: Do the `readOnly` and `disabled` attributes actually _disable_ the inputs too on IE? It should, but you never know with IE :)

A: Yes, the inputs are actually disabled for user input

**Comment by mikeverf** [comment]
@driesd Because we noticed the issue with the DatePicker, which didn't look disabled, but was still clickable as well (datepicker popover still popped up)

**Comment by driesd** [comment]
> @driesd Because we noticed the issue with the DatePicker, which didn't look disabled, but was still clickable as well (datepicker popover still popped up)

Yes I remember, that's why we took some action ;)

**Pull request merged**
