### PR TITLE
Progresstracker followup

### PR DESCRIPTION
**Pull request by lorgan3**
### Description

There were 2 minor details I noticed when actually using the component
 - When not at 100% zoom the bars could be misaligned in alternating mode
 - Colors of the bars didn't change at the same time as the bullets

### Manual check
- Enable 'alternating'
- Zoom in our out (for me it happened at 80% and 110%)
- The progresstracker should not be misaligned

### CODE REVIEW

**Review by driesd — APPROVED** [review]

**Comment by driesd** [comment]
✅  Manually checked

**Review by lowiebenoot — APPROVED** [review]
Added some knobs to the story as well.

**Comment by lorgan3** [comment]
Thanks. I've been using the toggles on the `docs` tab since most of the other components don't have knobs anymore 😅

**Comment by lowiebenoot** [comment]
@lorgan3 toggles on the docs tab? I don't see anything there? I might be missing something, was wondering why we didn't have much knobs anymore 😅

**Pull request merged**
