### PR TITLE
Bugfix: avoid using Math.max()

### PR DESCRIPTION
**Pull request by driesd**
### Description

Before this PR we were using `Math.max()` in our `Input` component. Apparently this was breaking the production deploy of our design-components CI. This was caused by Storybooks dependency usage of `babel-preset-minify`.

This PR avoids the usage of `Math.max()` by refactoring the code with an `if/else if` notation.

### Breaking changes

None.

### CODE REVIEW

**Comment by lowiebenoot** [comment]
Because that is not correct.

Top level: 

```
  "presets": [
    "@babel/preset-env",
    "@babel/preset-react",
    [
      "minify",
      {
        "builtIns": false
      }
    ]
  ],
```

**Comment by driesd** [comment]
As @lowiebenoot and I found out together, the `.babelrc` overrides (in all the formats mentioned above) simply don't work. We decided to close this PR because working around `Math.max()` works, but is no solid solution.

**Comment by stivni** [comment]
Hi all!

It's important that our storybook builds & deploys succeed again.
Can we first merge this PR and think about a better solution when we have a working build again?
Unless someone has a better alternative at the top of their mind?

Thanks!

**Comment by lowiebenoot** [comment]
Why is it important?

**Comment by stivni** [comment]
I assumed that teamleader.design serves as the documentation of how these components should be use and behave? (If not - why do we have it 🤔)

If so, documentation and code will slowly get out of sync, which will cause a lot of headaches.

Also : broken window syndrome. If a build/deploy break, fix it, before it gets worse, because than it'll become more difficult to fix.

**Comment by lowiebenoot** [comment]
We can still just run it locally.

I just think this is a ridiculous solution, for trying to use a broken alpha version. Where does it stop? Which functions can we use and which functions can't we use. 

Can't we deploy it in dev mode, so the minifying doesn't run?

**Comment by stivni** [comment]
@lowiebenoot you can do whatever you want, but the automatic builds need to be fixed

discuss, dismiss, ... but find a solution you can live with in that case

**Comment by duivvv** [comment]
How is this breaking the CI? What a strange situation :)

**Comment by lowiebenoot** [comment]
In the meanwhile, it isn't anymore. There was an issue with the building of storybook 4 alpha in production mode. But they (kind of) fixed it.

**Comment by lowiebenoot** [comment]
Also hard to discuss/dismiss if people don't answer...

**Pull request closed without merging**
