### PR TITLE
Add displayName to all components

### PR DESCRIPTION
**Pull request by driesd**
### Description

Due to Storybook's minification, all our component names are reduced to one or two random characters:
* `<n .../>`
* `<t .../>`
* `<Kn .../>`
* ...

This PR adds a displayName to all components, which solves the above issue.

#### Screenshot before this PR

schermafdruk 2018-11-09 12 06 50

schermafdruk 2018-11-09 12 07 00

#### Screenshot after this PR

schermafdruk 2018-11-09 12 06 30

schermafdruk 2018-11-09 12 07 11

### Breaking changes

None.

### CODE REVIEW

**Comment by driesd** [comment]
@nickwaelkens Unfortunately, `displayName` is not stripped out in production. According to `Dan Abramov`, this is not something they can do. The bundle size difference is *3kb*.

This PR is just a proposal to make out documentation readable again, because `there's no I in Teamleader UI`...

*With displayName*
734.255 bytes

*Without displayName*
731.361 bytes

Any more opinions?

**Comment by driesd** [comment]
Q: Is this 3kb considered `unnecessary clutter`, if you know that it helps all the frontenders, providing them with documentation that actually makes sense again?

**Comment by lowiebenoot** [comment]
Maybe you can just disable the minification?

**Comment by nickwaelkens** [comment]
Oh okay; I was expecting more than 3kB, but maybe-like @lowiebenoot suggests-we have to investigate why things are going wrong in Storybook?

**Comment by driesd** [comment]
> Maybe you can just disable the minification?

@lowiebenoot That is a very good solution!

In webpack.config.js I've added `storybookBaseConfig.optimization.minimize = false;`.

Bundle size stays the same as before. And now I only need to add displayName to the Typography components, because they are wrapped in a factory.

This PR will be closed and a new one will be opened. Many thx!

**Comment by duivvv** [comment]
I just assumed that was not an option. 😕

**Comment by driesd** [comment]
I actually had the same assumption and thought it would result in unwanted side effects...

**Pull request closed without merging**
