### PR TITLE
[TU-95] Split up Text and Headings into separate components

### PR DESCRIPTION
**Pull request by driesd**
### Description

This PR splits up our `Text` component into separate components:
* Heading1
* Heading2
* Heading3
* Heading4
* TextDisplay
* TextBody
* TextSmall

**Main reason for this:** the documentation in Storybook just wasn't right. It was displaying the wrong component names. Also there were way too much prop tables shown, which was far from clear to other developers. 

#### Screenshot before this PR

schermafdruk 2018-08-02 16 38 09

schermafdruk 2018-08-02 16 38 31

#### Screenshot after this PR

schermafdruk 2018-08-02 16 36 16

schermafdruk 2018-08-02 16 36 30

### Breaking changes

None.

### CODE REVIEW

**Comment by lowiebenoot** [comment]
It's a bit sad though, that so many code is repeated now, instead of just having the factory.

**Comment by driesd** [comment]
I know, It is a bit sad idd... But at least the documentation is now correct! :)

**Comment by nickwaelkens** [comment]
I have to agree with @lowiebenoot - this will add quite some duplicate code to our (already quite big) bundles, right? All that, just so we can get something working that is probably considered a bug in Storybook? Have you tried opening an issue on their repo, ask for pointers?

We should get to the root of the problem instead 🤔

**Comment by thomasnoe07** [comment]
@driesd  Can this PR get moving again or is it blocked?

**Comment by driesd** [comment]
-

**Pull request closed without merging**
