### PR TITLE
update code owners

### PR DESCRIPTION
**Pull request by farazatarodi**
### Description

Adds @farazatarodi and @lowiebenoot to the code owners.

### CODE REVIEW

**Comment by driesd** [comment]
Can you add a new line to the end of the file? 😊

**Comment by qubis741** [comment]
Can you also update contributors in `package.json` please?

**Review by eniskraasniqi1 — APPROVED** [review]

**Comment by farazatarodi** [comment]
@qubis741 update in what way? Add myself or remove everyone else?

**Review by JorenSaeyTL — APPROVED** [review]

**Review by KristofColpaert — APPROVED** [review]

**Review by lorgan3 — APPROVED** [review]

**Comment by qubis741** [comment]
> @qubis741 update in what way? Add myself or remove everyone else?

remove non-working devs, add missing devs that works on this

**Comment by farazatarodi** [comment]
@qubis741 I forgot to answer. sorry, my bad! Everyone is still a contributor and will work on this. I added code owners for reviews only :)

**Pull request merged**
