### PR TITLE
[Chore] Bump draft-js

### PR DESCRIPTION
**Pull request by lorgan3**
### Description
Fixes a security issue
There should be no major differences. Changelog here: https://github.com/facebook/draft-js/releases/tag/v0.11.7

### CODE REVIEW

**Review by mikeverf — APPROVED** [review]

**Comment by lorgan3** [comment]
Specifically to get rid of this one
```
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ low           │ Denial of Service                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ node-fetch                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=2.6.1 <3.0.0-beta.1|| >= 3.0.0-beta.9                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @teamleader/ui                                               │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @teamleader/ui > draft-js > fbjs > isomorphic-fetch >        │
│               │ node-fetch                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://www.npmjs.com/advisories/1556                        │
└───────────────┴──────────────────────────────────────────────────────────────┘
```

**Review by driesd — APPROVED** [review]

**Comment by mikeverf** [comment]
FYI: this is used for the WysiwygEditor; so as long as that still works fine, we're good
Although I don't thing there should be any problem

**Review by sanderbrugge — APPROVED** [review]

**Comment by lorgan3** [comment]
@mikeverf Yep I gave it a (very quick) and and it still worked.

Feel free to also give it an mc 😄

**Review by ArnaudWeyts — APPROVED** [review]

**Review by lowiebenoot — APPROVED** [review]

**Comment by ArnaudWeyts** [comment]
✅ wysiwygeditor still seems to work fine

**Pull request merged**
