### PR TITLE
fix/reviewer lottery

### PR DESCRIPTION
**Pull request by farazatarodi**
Runs the job on ubuntu

### CODE REVIEW

**Review by driesd — APPROVED** [review]

**Review by stefaandevylder — APPROVED** [review]

**Review by jelledc — APPROVED** [review]

**Comment by YorickH** [comment]
@farazatarodi Do we need to follow this up to add the necessary dependencies onto our self-hosted runner?

**Comment by farazatarodi** [comment]
@YorickH your call. For us there is no difference. But I would set both jobs (this and chromatic) to self-hosted in that case.

**Comment by YorickH** [comment]
@farazatarodi Why did you move it to the github hosted instances? Any error in specific?

**Comment by farazatarodi** [comment]
@YorickH `Requested labels: self-hosted
Job defined at: teamleadercrm/ui/.github/workflows/reviewer-lottery.yaml@refs/heads/next-release
Waiting for a runner to pick up this job...`

**Pull request merged**
