### PR TITLE
Release 8.2.0

### PR DESCRIPTION
**Pull request by ArnaudWeyts**
### Changed

- `ProgressTracker`: Adjust vertical spacing ([@lorgan3](https://github.com/lorgan3) in [#1784](https://github.com/teamleadercrm/ui/pull/1784)

### Fixed

- `types`: Fix types for components with static properties ([@ArnaudWeyts](https://github.com/ArnaudWeyts) in [#1789](https://github.com/teamleadercrm/ui/pull/1789)

### CODE REVIEW

**Review by lorgan3 — COMMENTED** [review]
You lost a bracket when moving the items in the changelog

**Comment by lorgan3** [comment]
Also Q: Do we just ignore dependency updates for future updates or only document major changes?

**Comment by ArnaudWeyts** [comment]
> You lost a bracket when moving the items in the changelog

Urgh, we need to automate this process already 🙈 will fix it

**Comment by ArnaudWeyts** [comment]
> Also Q: Do we just ignore dependency updates for future updates or only document major changes?

To be honest, I believe most dependency updates should probably be ignored as they are not relevant to end users, especially the dev dependencies updates.

**Pull request merged**
