### PR TITLE
Fix Dialog content blurriness in webkit

### PR DESCRIPTION
**Pull request by ArnaudWeyts**
### Description

- `Dialog, DialogBase`: Fix blurriness with certain text content in webkit-based browsers

#### Screenshot before this PR

Screenshot 2022-06-03 at 15 38 42

#### Screenshot after this PR

Screenshot 2022-06-03 at 15 38 20

### Manual check

- [ ] The dialogs still render and animate in correctly

### CODE REVIEW

**Review by stefaandevylder — DISMISSED** [review]
Damn, 👍🏼 nice solution!

**Review by jelledc — DISMISSED** [review]

**Review by qubis741 — APPROVED** [review]

**Comment by qubis741** [comment]
Manual check failed :rotating_light: Blurred text is fixed but Dialog is not draggable anymore

**Review by qubis741 — CHANGES_REQUESTED** [review]
MC failed

**Review by lowiebenoot — APPROVED** [review]

**Review by stefaandevylder — APPROVED** [review]

**Review by eniskraasniqi1 — APPROVED** [review]
Manually checked 🟢 , dialog renders and animates correctly!

**Comment by ArnaudWeyts** [comment]
Manually checked the Dialog on the published Chromatic storybook ✅

**Pull request merged**
