### PR TITLE
Update prettier version

### PR DESCRIPTION
**Pull request by LennertBlommaert**
### Description
This PR updates the `prettier` version, as the previous version gave errors while running pre-commits.

### CODE REVIEW

**Comment by duivvv** [comment]
what were the errors? sounds a bit drastic?

**Comment by LennertBlommaert** [comment]
@duivvv I was unable to commit as the `pre-commit hook failed`.
Here a screenshot of the logging in my terminal:
screen shot 2018-07-18 at 10 02 14

**Comment by duivvv** [comment]
What is your installed `pretty-quick` version (not the one in the package.json, the actual installed one)

**Comment by LennertBlommaert** [comment]
The installed `pretty-quick` version is `1.6.0` (which is also the latest version)

**Comment by duivvv** [comment]
it has a peer dependency `"prettier": ">=1.8.0"`

so update away (and re-run prettier on the whole codebase)

**Comment by duivvv** [comment]
👍 

Could you also add a script to `package.json` for future updates.

`prettier --write '**/*.{js, json, md, css}'` I think

**Pull request merged**
