### PR TITLE
Make MarketingDialog draggable

### PR DESCRIPTION
**Pull request by BeirlaenAaron**
### Description

Allow the Dialog component to have no footer and convert MarketingDialog to it so it's draggable

#### Screenshot before this PR

image

#### Screenshot after this PR

[Screencast from 19-09-22 16:10:29.webm](https://user-images.githubusercontent.com/55881661/191038282-73944581-1a43-4a06-965e-d5661001c69f.webm)

### Breaking changes

N/A

### CODE REVIEW

**Review by lorgan3 — COMMENTED** [review]
This a mostly personal preference but I would rather reimplement the dragging functionality in the marketing dialog because now we're making the `Dialog` more like the `DialogBase` which is not a good thing I think. The way I see it, the `Dialog` component is supposed to force you to be consistent (Which the marketing dialog is not)

Let's see what the others think though.

**Comment by stefaandevylder** [comment]
Personally I don't see the reason why you would need to be able to drag a marketing dialog, either you interact with it or click it away 🤔 But thats just my opinion

**Comment by BeirlaenAaron** [comment]
> Personally I don't see the reason why you would need to be able to drag a marketing dialog, either you interact with it or click it away thinking Any other functional dialog makes sense tho. But thats just my opinion Edit: This might be a good question for a marketeer

I noticed it was draggable in the [design](https://www.figma.com/file/aPFtL8DksaB0Js4g7m5RMk/Vectera-MVP-designs-(September-implementation)?node-id=1%3A21546) and thought I'd change it while I was at it

**Review by adognameddog — APPROVED** [review]

**Review by JorenSaeyTL — APPROVED** [review]

**Comment by jelledc** [comment]
> This a mostly personal preference but I would rather reimplement the dragging functionality in the marketing dialog because now we're making the `Dialog` more like the `DialogBase` which is not a good thing I think. The way I see it, the `Dialog` component is supposed to force you to be consistent (Which the marketing dialog is not)
> 
> Let's see what the others think though.

I agree.

**Pull request closed without merging**
