### PR TITLE
bump version to 14.2.0

### PR DESCRIPTION
**Pull request by farazatarodi**
### Description

Adds onClick to Widget Header

### CODE REVIEW

**Comment by lorgan3** [comment]
The changelog will also need to be updated. (See [how to make a release)](https://github.com/teamleadercrm/ui#how-to-make-a-release)
Any chance https://github.com/teamleadercrm/ui/pull/2085 can also be included? 😅

**Comment by farazatarodi** [comment]
@lorgan3 changelog is already bumped with my previous PR

**Review by stefaandevylder — DISMISSED** [review]

**Comment by ArnaudWeyts** [comment]
We'll need to include @lorgan3's change in the same release, since it's already merged

**Review by lorgan3 — APPROVED** [review]

**Comment by ArnaudWeyts** [comment]
Should you have merged the next-release branch @farazatarodi ? I think once you merge this the same entry will be present in "unreleased"

**Comment by farazatarodi** [comment]
wrong merge and commit

**Comment by farazatarodi** [comment]
Wrong merge and commit

**Pull request closed without merging**
